version: "2"
services:
  wallabag:
    image: wallabag/wallabag
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} #1q2w3e4r5t6y7u8i9o0p
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=${SYMFONY__ENV__DATABASE_HOST} #192.168.1.78
      - SYMFONY__ENV__DATABASE_PORT=${SYMFONY__ENV__DATABASE_PORT} #3306
      - SYMFONY__ENV__DATABASE_NAME=${SYMFONY__ENV__DATABASE_NAME} #wallabag
      - SYMFONY__ENV__DATABASE_USER=${SYMFONY__ENV__DATABASE_USER} #wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=${SYMFONY__ENV__DATABASE_PASSWORD} #wallapass
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__MAILER_HOST=${SYMFONY__ENV__MAILER_HOST} #127.0.0.1
      - SYMFONY__ENV__MAILER_USER=${SYMFONY__ENV__MAILER_USER} #~
      - SYMFONY__ENV__MAILER_PASSWORD=${SYMFONY__ENV__MAILER_PASSWORD} #~
      - SYMFONY__ENV__FROM_EMAIL=${SYMFONY__ENV__FROM_EMAIL} #wallabag@example.com
      - SYMFONY__ENV__DOMAIN_NAME=${SYMFONY__ENV__DOMAIN_NAME} #https://pages.mbwnetworks.com
      - SYMFONY__ENV__SERVER_NAME=${SYMFONY__ENV__SERVER_NAME} #"Mukesh's pages instance"
    ports:
      - 8765:80
    volumes:
      - /portainer/Files/AppData/Config/Wallabag/data:/var/www/wallabag/data
      - /portainer/Files/AppData/Config/Wallabag/images:/var/www/wallabag/web/assets/images
    depends_on:
      - wallabagredis
  wallabagredis:
    image: redis:latest