version: '3'

services:
  keycloak-db:
      container_name: keycloak-db
      image: postgres:13
      restart: always
      volumes:
        - /portainer/Files/AppData/keycloak/container-data/db:/var/lib/postgresql/data:Z
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      networks:
        - keycloak-nw
  keycloak:
      container_name: keycloak
      image: quay.io/keycloak/keycloak:latest
      restart: always
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: keycloak-db
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: ${POSTGRES_PASSWORD}
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
        PROXY_ADDRESS_FORWARDING: 'true'
       #ports:
       #  - 8081:8081
      depends_on:
        - keycloak-db
      networks:
        - reverseproxy-nw
        - keycloak-nw
        
networks:
    keycloak-nw:
