################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
################################################################################
version: "2"

services:
  node-red:
    image: nodered/node-red:latest
    restart: always
    environment:
      - TZ=America/New_York
      - NODE_RED_CREDENTIAL_SECRET=${NODE_RED_CREDENTIAL_SECRET}
    ports:
      - 1880:1880
    networks:
      - node-red-net
    volumes:
      - /portainer/Files/AppData/node-red/data:/data:Z

networks:
  node-red-net: