version: '3'
services:
  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb
    volumes:
      - /portainer/Files/AppData/nocodb/container-data/data:/usr/app/data
    restart: always
    ports:
      - "8631:8080"
    environment:
      NC_DB: ${NC_DB_STRING} #"mysql2://root_db:3306?u=noco&p=password&d=root_db"
      NC_AUTH_JWT_SECRET: ${NC_AUTH_JWT_SECRET}